### ISSUE TITLE
FYI about multipart stream factories

### ISSUE THREAD

**Issue by Nyholm** [http-interop/http-factory#10]
I want to you know that I tried working on a multipart stream factory a couple of months back. The original PR is found [here](https://github.com/php-http/message-factory/pull/30). My summary what multipart streams is all about and some issues is found [here](https://github.com/php-http/message-factory/issues/31). I sum up the work [here](https://github.com/php-http/message-factory/pull/30#issuecomment-233652431) where I say: 

> We stopped the discussion because we did not want to define a MultipartStreamInterface (the return value of the factory). Instead we changed the way we look at multipart streams. If we consider them as normal streams that you create in a very specific way we would not need a MultipartStreamInterface. 
> 
> We created a PSR-7 independent [MultipartStreamBuilder](https://github.com/php-http/multipart-stream-builder) to help us create Streams in this very specific way. Read about it in the docs: http://php-http.readthedocs.io/en/latest/components/multipart-stream-builder.html
> 
> I suggest we wait to create a MultipartStreamFactory until PHP-Fig has an interface for such implementation. 

My question is: Is multipart streams something we want to support in our StreamFactory (or a new MultipartStreamFactory)? Or do we want to leave this outside of PSR-17 and recommend users to the [MultipartStreamBuilder](https://github.com/php-http/multipart-stream-builder) for now?

**Comment by shadowhand** [comment]
I think that this would be another great addition to `http-interop`. I do not think it should be added to PSR-17, as the intent is to create factory specifications only for PSR-7 interfaces. Adding too much will derail the process, I'm afraid.

From reading the discussions it is not clear to me if `MultipartStream` can extend `Stream` or not. Can you clarify this point?

**Comment by Nyholm** [comment]
A MultipartStream is just a normal stream with a special body. What's makes the body special is the `$boundary`. 

Both of these are valid. One must just make a decision.

``` php
// Option A)
interface MultipartStreamInterface extends StreamInterface {}

// Option B)
interface MultipartStreamInterface extends StreamInterface {
  public function getBoundary();
}
```

If we choose option A (which I prefer) we do not need to alter PSR-7 and we could have a factory that looks like this: 

``` php
class MultipartStreamFactory {
  /**
   * @return StreamInterface PSR-7
   */ 
  public function create($boundary, $dataInSomeFormat) {
    // ..
  }
}
```

As you can see from the [docs for the MultipartStreamBuilder](http://php-http.readthedocs.io/en/latest/components/multipart-stream-builder.html#building-a-multipart-stream) the user needs to know of the value of `$boundary` in order to set the headers properly.

**Comment by shadowhand** [comment]
I would suggest creating a separate package for multi-part streams. I think adding this to `http-factory` itself would be out of scope.

**Comment by mindplay-dk** [comment]
> I would suggest creating a separate package for multi-part streams. I think adding this to http-factory itself would be out of scope.

Definitely agree - as mentioned in another thread, I think we should stick to dealing with stream types that deal with PHP and OS resources; more specialized stream-types are probably rarely used, and, in many cases, are going to depend on too many implementation details for us to define a meaningful description/interface.

**Comment by Nyholm** [comment]
Sure, Let's decide it out of scope.
