### ISSUE TITLE
creating a standalone unit test for the http factory implementations

### ISSUE THREAD

**Issue by nyamsprod** [http-interop/http-factory#13]
One of the problem with current PSRs (specifcally PSR-7) is that they do not offer a test suite to validate independent implementation. With the HTTP factory I believe this could be one strong argument to enable easier adoption if such test  suite was provided. What are your thoughts on providing such independent package ?

**Comment by Nyholm** [comment]
I like it. I created such test suite for psr6 and it is widely used and appreciated. 

:+1:

**Comment by mindplay-dk** [comment]
Great idea!

**Comment by shadowhand** [comment]
I like the idea.

**Comment by Nyholm** [comment]
I've created https://github.com/Nyholm/http-factory-tests

If someone create a repository at http-interop I'll be happy to push my repository here.

**Comment by shadowhand** [comment]
@Nyholm you can email Github and ask them to transfer ownership to `http-interop`.

**Comment by shadowhand** [comment]
The repository has been moved. Thanks!

https://github.com/http-interop/http-factory-tests
