### ISSUE TITLE
Create a repo for Guzzle

### ISSUE THREAD

**Issue by Nyholm** [http-interop/http-factory#17]
I want to try out an factory implementation of Guzzle. I ended up with: https://github.com/Nyholm/http-factory-guzzle

If you create `http-interop/http-factory-guzzle` I would be happy to push the code there.

**Comment by Nyholm** [comment]
I also added Slim. https://github.com/Nyholm/http-factory-slim

Note the RequestFactory. Slim uses the same object for ServerRequestInterface as RequestInterface

**Comment by shadowhand** [comment]
You can transfer ownership to http-interop by doing a Transfer Ownership request from the repository settings. HTTP Interop will be happy to take these packages as long as they are MIT licensed.

**Comment by Nyholm** [comment]
Thank you. That is great. 

I've transfered the repos now.
