### ISSUE TITLE
extraneous ServerRequestFromGlobalsFactoryInterface?

### ISSUE THREAD

**Issue by mindplay-dk** [http-interop/http-factory#18]
I'd like to suggest that the `ServerRequestFromGlobalsFactoryInterface` is unnecessary, and may in fact harm, rather than help, in terms of interop.

Since we have `ServerRequestFactoryInterface`, it is in fact possible to write _one_ implementation of a factory that creates a server-request from globals, and this factory will work for _any_ implementation of PSR-7 supported by the other HTTP factory interfaces.

``` php
class GlobalServerRequestFactory
{
    private $srf, $urif, $upf;

    public function __construct(
        ServerRequestFactoryInterface $srf,
        UriFactoryInterface $urif,
        UploadedFileFactoryInterface $upf
    ) {
        $this->srf = $srf;
        $this->...
    }

    /**
     * @return ServerRequestInterface
     */
    public function createServerRequestFromGlobals()
    {
        return $this->srf->createServerRequest(
            $_SERVER['REQUEST_METHOD'],
            "http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']
        )
            ->withHeaders(...)
            ->withFiles(...)
            ...;
    }
}
```

Of course, you could do that whether `ServerRequestFromGlobalsFactoryInterface` exists or not, but the point is, if a single implementation of `ServerRequestFromGlobalsFactoryInterface` will work for all implementations of PSR-7, then how does it matter which implementation of a global server request factory you're using?

It'll produce a global server request using _any_ PSR-7 implementation using an implementation of the other factory interfaces - which is all that matters in terms of interop, is it not?

**Comment by oscarotero** [comment]
Hello.
I suggest that `createServerRequestFromGlobal` accepts optionally (or required, I don't mind) arguments with the global values. I mean:

``` php
$serverRequest = $factory->createServerRequestFromGlobals($_SERVER, $_GET, $_POST, $_FILES, $_COOKIES, 'php://input');
```

This allows to create fake server request easily. I did something similar in [a http library](https://github.com/fol-project/http/blob/master/src/Globals.php) (now abandoned) and it was really useful.

**Comment by mindplay-dk** [comment]
@oscarotero no argument there, although I'm not sure what your point is in relation to this issue? The point I'm making, is that someone can implement this factory class _once_, and it will work for _any_ implementation of PSR-7, as long as it has an implementation of the primary factory interface.

**Comment by oscarotero** [comment]
@mindplay-dk I'm agree with you that using global values to create a server request can be implemented once and be used by all psr-7 implementations, but there's some issues to keep in mind:
- The server params cannot be changed after instantation (there's no a `withServerParams`) so it must be passed to the constructor, or be taken by the constructor from the global `$_SERVER` (that I disagree).
- This means that method and uri (the arguments currently defined in the server request factory) could be taken from the server params. In other words: `createServerRequest($server, $method, $uri)` makes no sense for me, `createServerRequest($server)` is enought.
- But if we detect these params from the `$server` array, we are implementing part of the `createServerRequestFromGlobals` logic into the constructor, because there's various ways to [detect the method](https://github.com/fol-project/http/blob/master/src/Globals.php#L115) and to [detect the uri](https://github.com/fol-project/http/blob/master/src/Globals.php#L105)

**Comment by mindplay-dk** [comment]
@oscarotero okay, wow, that's weird. Why does PSR-7 not include `withServerParams()`? How is one supposed to override/manipulate (or test!) with different server-params?

The absence of this feature in PSR-7 appears to mean that, yes, we are going to need a dedicated "server-request from globals" factory.

I find that really problematic. Any idea why this method is absent? (I poked through the meta-document for PSR-7 and could find no explanation.)

**Comment by oscarotero** [comment]
I remember to read something in the php-fig mailing list some time ago but I cannot find it right now. The server array contains information about the environment in which the request is created, so it's not part of the http information that you can modify (headers, body, parsed body, uri, etc), but contains data returned by the SAPI. Being this info inmutable, allows to restore the initial data about the request.

This means that we can get different values calling `$request->getMethod()` and `$request->getServerParams()['REQUEST_METHOD']`. So, after thinking more about this, maybe it's not bad idea to have a factory with the following signature: `createServerRequet($server, $method, $uri)` because `$method` and `$uri` are no required to match with `$server` data.

An idea: instead having a factory to create a server request from globals, we could have a library to normalize the request acording to the server params.

``` php
$request = $factory->createServerRequest($_SERVER, 'GET', '/');
$request = $normalizer->normalize($request);
```

**Comment by mindplay-dk** [comment]
@oscarotero normalizing the request after the fact seems backwards to me.

Also, the `$server` argument isn't going to make any sense in most cases, meaning all cases except creating the request from globals - so it doesn't make much sense to require that as the first argument.

It seems that creating a server-request is a substantially different task from creating a server request from globals after all.

So my recommendation would be two distinct factory signatures, as I proposed initially - and for the global request factory, more or less, referencing the argument list from global server-request factory in diactoros, which permits either injecting from superglobals (by default) or overriding for testing purposes.

Creating vanilla server requests is a much simpler and more predictable task, so I think we should not complicate the generic server-request factory by overloading with the apparently quite different task of creating from superglobals.

**Comment by oscarotero** [comment]
Or maybe we should not include the `createServerRequestFromGlobals` factory in this package, because it's a specific implementation, like streams created from callbacks or something like this.

**Comment by mindplay-dk** [comment]
> Or maybe we should not include the `createServerRequestFromGlobals` factory in this package, because it's a specific implementation, like streams created from callbacks or something like this.

I think those are two very different situations?

Streams from callbacks aren't defined by the underlying abstraction - only one, generic type of stream is defined by PSR-7.

As opposed to requests - two different types of requests are defined by PSR-7, so I think that we must support creation of both, otherwise we're not fully supporting PSR-7.

**Comment by oscarotero** [comment]
I mean do not include a `createServerRequestFromGlobals`, just a `createServerRequest`, so both request types are supported. The `createServerRequestFrom[Whatever]` factory is a implementation feature.

**Comment by mindplay-dk** [comment]
No, you're right - there should be only one factory.

Otherwise we're forcing every implementer to duplicate a [very complex factory implementation](https://github.com/zendframework/zend-diactoros/blob/master/src/ServerRequestFactory.php), for no apparent reason - one could simply adjust this factory implementation to rely on the first interface, rather than re-implementing it again and again.

Incidentally, this is precisely the same question as with the stream-factory.

I realize that this factory is considerably more complex than the various stream factory implementations, but the issue and question is precisely the same.

I feel that there is an inconsistency in the logic and decision-making here, but, yeah - I definitely agree that only one factory is needed here.

I wish you would apply the same logic to the stream-factory, but yeah...

**Comment by shadowhand** [comment]
@mindplay-dk I split the factory based on your insistence that I do so. Now it is okay to just have one interface with two methods?! Or is the suggestion that we drop the basic `createServerRequest` method in favor of one that only creates from globals?

Honestly, I am getting a little bit frustrated with all the back and forth about these interfaces and what methods they contain. There is clear precedent in the existing packages that implement `ServerRequestInterface` for including a method that generates a server request from globals. In fact, there is far more precedent for that than any other method.

Part of me is inclined to only take feedback from those that are directly involved with a major PSR-7 implementation (Zend, Guzzle, Slim) to stop this bikeshedding.

**Comment by mindplay-dk** [comment]
> I split the factory based on your insistence that I do so. Now it is okay to just have one interface with two methods?! Or is the suggestion that we drop the basic `createServerRequest` method in favor of one that only creates from globals?

No, I'm suggesting that the "server request from globals" factory isn't necessary at all.

Creating one specific implementation of `ServerRequestInterface` requires precisely one method.

I don't believe we need a "server request from globals" factory method at all, and that's what @oscarotero pointed out - because it's a [fairly complex thing](https://github.com/zendframework/zend-diactoros/blob/master/src/ServerRequestFactory.php), and there is zero benefit to making everyone implement this again and again, when it could actually be implemented once and support all implementations of `ServerRequestInterface` by injecting any server request factory.

If we _do_ include the "server request from globals" factory-method, it _must_ be a separate interface, since otherwise we're unnecessarily _forcing_ everyone to duplicate this factory-method.

_If_ included, this interface must be optional, e.g. must be seen as an interface to be implemented by a _global_ server-request factory, which has very different use-cases from the regular server-request factory.

Omitting or including the global server-request factory is honestly not an important point for me. What's important is that, if we _do_ include it, it's separate, so that the _community_ can decide if they want to implement a generic "server request from globals" factory that implements just that interface, or, if they prefer, they can implement both interfaces with one class; which I hope that they won't, because there is zero benefit to having duplicating implementations of the global server-request factory.

Either way, if included, it must be a separate interface, since otherwise we really are dictating architecture and forcing duplication, both of which are pretty horrible.

> Honestly, I am getting a little bit frustrated with all the back and forth about these interfaces and what methods they contain

It's frustrating, but isn't that basically what this process is? Coming to agreement on things that have to be finite, and have to work for everyone, for everything, is not a simple task.

I do feel like we've made progress though. Not that it isn't slow and frustrating, but I think that's pretty much unavoidable.
