### ISSUE TITLE
StreamFactory createStreamFromStreams

### ISSUE THREAD

**Issue by schnittstabil** [http-interop/http-factory#26]
If we want *PSR-15 Single Pass (Lambda) Middlewares* to become a success story, then we need a way to combine/concatenate PSR-7 Streams:

```php
// Double Pass example from the Slim user guide:
function ($request, $response, $next) {
    $response->getBody()->write('BEFORE');
    $response = $next($request, $response);
    $response->getBody()->write('AFTER');

    return $response;
};
```

As far as I can see, with [`GuzzleHttp\Psr7\AppendStream`](https://github.com/guzzle/psr7#appendstream), it is actually possible to do the same with *Single Pass*:

```php
use GuzzleHttp\Psr7\AppendStream;

public function process(ServerRequestInterface $request, DelegateInterface $delegate)
{
    $response = $delegate->process($request);
    $body = new AppendStream([
        $this->streamFactory->createStream('BEFORE'),
        $response->getBody(),
        $this->streamFactory->createStream('AFTER'),
    ]);
    $response = $response->withBody($body);

    return $response;
}
```

I'm only familiar with Node.js streams in depth, thus: maybe there is an easier way?
Otherwise, my two cents:
```php
StreamFactoryInterface::createStreamFromStreams(array $streams)
```

**Comment by shadowhand** [comment]
I don't think this is at all required for PSR-17. It looks more like a utility package that defines a stream composed of other streams.

**Comment by mindplay-dk** [comment]
This doesn't look like a realistic use-case.

If you were going to manipulate the body of a response, there are very few (any?) use-case where you can simply append to the start or end of the body and end up with anything meaningful.

A real use-case would be something that, say, rewrites URLs in an HTML body - but that requires you to filter and replace the entire body, which you can already do.

As far as I can figure, there will be almost no real use-cases where you can simply concatenate streams.

**Comment by schnittstabil** [comment]
The issue I see is, that current double-pass middlewares can do that and I believe they already do it. E.g. one gets a really simple template mechanism – yes, this could also be done in memory as well:

```php
public function process(ServerRequestInterface $request, DelegateInterface $delegate)
{
    $response = $delegate->process($request);
    $body = (string) $response->getBody();
    $body = $this->streamFactory->createStream('<html…'.$body.'…</html>'),

    return $response->withBody($body);
}
```

But we need to read the whole body, which contradicts the whole *stream* idea in my opinion.

**Comment by shadowhand** [comment]
A person could create a `composite-stream` package that implements `StreamInterface` that contains a collection of streams. Ultimately, the entire stream will have to be read and merged, so I think your last example isn't really a problem, @schnittstabil.
