### ISSUE TITLE
ResponseFactory body

### ISSUE THREAD

**Issue by atanvarno69** [http-interop/http-factory#27]
As written, `ResponseFactory` makes no guarentee about its body `StreamInterface` -- it could be read-only, non-seekable or non-existent.
```php
$response = $responseFactory->createResponse();
$response->getBody()->write('Content'); // not sure if this will work
$response->getBody()->rewind(); // or this
```
In the context of PSR-15 middleware, if I want to return a response without calling the remaining middleware stack/queue, I need to pass instances of both `ResponseFactoryInterface` *and* `StreamFactoryInterface` into my constructor (or setter, whatever).

Or I can call the remaining stack/queue just for a response object to put my stream into, despite knowing I'm going to disregard all the processing the remaining stack does on the request and response. Needlessly calling the rest of the stack seems wasteful and bad, so I stick with the two factories above.

This isn't intolerable or anything, it would just save a little boilerplate in any middleware that wants to return a response without calling the rest of the stack/queue (eg, an error response) if `ResponseFactoryInterface::createResponse()` guaranteed that its resulting response came with body that was writable and seekable.

**Comment by shadowhand** [comment]
>  I need to pass instances of both `ResponseFactoryInterface` and `StreamFactoryInterface` in[to]

This would be the correct thing to do. The example at the top of the issue is the current status quo with double-pass middleware and has been shown to be error prone.
