### ISSUE TITLE
createStreamFromFile and fopen warnings

### ISSUE THREAD

**Issue by schnittstabil** [http-interop/http-factory#28]
As far as I can see, it is not explicitly defined what happens, if the file cannot be opened:
```php
/**
 * Create a stream from an existing file.
 *
 * The file MUST be opened using the given mode, which may be any mode
 * supported by the `fopen` function.
 *
 * @param string $file
 * @param string $mode
 *
 * @return StreamInterface
 */
public function createStreamFromFile($file, $mode = 'r');
```

[`Http\Factory\Diactoros\StreamFactory`](https://github.com/http-interop/http-factory-diactoros/blob/aec9db2b8ef550e239988f0e01e01b793e1c9ae1/src/StreamFactory.php#L21) for example simply calls `fopen($file, $mode)`, which may cause a warning. This is usually not desired, especially in security related contexts. I believe an exception would be more appropriate, wouldn't it?

**Comment by shadowhand** [comment]
Yes.

**Comment by mindplay-dk** [comment]
We can close this, can't we?

**Comment by shadowhand** [comment]
We need to update our interfaces too.
