### ISSUE TITLE
What data is createServerRequestFromArray supposed to fill?

### ISSUE THREAD

**Issue by Zegnat** [http-interop/http-factory#32]
I originally posted this to the PHP-FIG mailing list ([[PSR-17] Document what must and mustn’t be set by createServerRequestFromArray?](https://groups.google.com/forum/#!topic/php-fig/T0eInLpcsS4)), but maybe this is the correct place instead.

---

Hi,

I was recently looking at the latest changes to the PSR-17 proposal made in commit [3166325](https://github.com/php-fig/fig-standards/commit/31663251d3fc37653ab1441035a8ed187736b2b1) and while I agree with the change itself (splitting into two separate methods), my main concern is about the complete removal of the following sentence:

> The method and URI of the request SHOULD be derived from the given server parameters.

This was previously the only guidance in the PSR as to what property values should be assigned to the ServerRequest by the factory. Leaving this completely open would, I believe, make different factory implementations incompatible with each other.

Implementations might make `#createServerRequestFromArray()` follow `#createServerRequest()` and only set the method and URI based on the array. Others might assign the server parameters, which I would argue is the expected (but undocumented) behaviour of `createServerRequestFromArray` versus `createServerRequest`. Library users switching implementation could run into this difference when `#getServerParams()` suddenly starts returning unexpected different results.

As the server parameters are read-only, a more dangerous implementation difference could be the assignment of headers to the ServerRequest based on what they find in the provided array. (`$_SERVER` includes HTTP headers as `HTTP_*` values.) As the documentation does not mention headers, implementations can make their own choice on what they will do. If a library user is used to having to add the headers themselves, they might loop over some soft of header collection and call `#withAddedHeader()` on the ServerRequest. In the case of an implementation that does not add headers, this will work fine, while the user otherwise ends up with a load of duplicated headers on their ServerRequest.

I would propose clarifying the documentation on `#createServerRequestFromArray()` to specify what must and mustn’t be set on the newly created ServerRequest. The following things come to mind:

* Specify that the passed `$server` **MUST** or **MUST NOT** be set as the result for `#getServerParams()`. Do not leave this up to the interpretation of the implementer.
* Specify that the results for `#getMethod()` and `#getUri()` **MUST** be set based on `$server`. This is currently implied by the documented `@throws` only.
* Specify what other information **MUST** or **MUST NOT** be extracted. E.g. header information, which is available in `$_SERVER` but should either always be added by implementers or never as it otherwise makes for different ServerRequest instances that need different follow-up.

**Comment by shadowhand** [comment]
Yes, this is a good idea. Right now the assumption is "as much as possible" but too is vague. You're absolutely right that (at minimum) the method and URI should be pulled from the server array. I would also expect the protocol version, headers, and query string parameters to be loaded.

I would **not** expect the request body to be attached, so that should be explicitly noted as well. As a side note, I am fairly certain that both the Guzzle and Diactoros factories do, in fact, load the request body when using `createServerRequestFromArray`.

We'll need to come up with a definitive list of what is expected and not expected.

**Comment by Zegnat** [comment]
> I would also expect the <i>[…]</i> query string parameters to be loaded.

This brings up the question whether the created ServerRequest’s `#getQueryParams()` has to be filled for `#createServerRequest()` as well. If `#createServerRequestFromArray()` has to fill it, it has to come from parsing the URI. There is no reason why `#createServerRequest()` could not parse its URI as well.

> I would **not** expect the request body to be attached, so that should be explicitly noted as well.

PHP’s own `$_SERVER` includes no way to access the request body, as far as I know. So I am not sure if this needs to be explicitly noted. It wouldn’t be possible. (Diactoros’ ServerRequestFactory’s `#fromGlobals()` requires a separate input for the request body.)

**Comment by shadowhand** [comment]
Diactoros [automatically parses `php://input`](https://github.com/zendframework/zend-diactoros/blob/master/src/ServerRequestFactory.php#L72).

**Comment by Zegnat** [comment]
> Diactoros [automatically parses `php://input`](https://github.com/zendframework/zend-diactoros/blob/master/src/ServerRequestFactory.php#L72).

Don’t know how I missed that one, thanks! That feels incredibly wrong to me though, I don’t think the factory should use anything that wasn’t passed on to it through its method call.

Maybe the documentation needs to forbid defaulting to `php://input` (body) or `apache_request_headers` (headers) when data is not in the passed `$server` array?

**Comment by Nyholm** [comment]
I also agree that this should be documented. 

But Im not sure how much we should require of the implementation. Should we force everyone to provide a body, headers, query string etc? Or should we leave things up to the implementations itself? 

**I think** that we should require Method and URI. I have not strict opinion of other parameters.

**Comment by Zegnat** [comment]
> Should we force everyone to provide a body, headers, query string etc? Or should we leave things up to the implementations itself?

The problem is that factory implementations will no longer be interchangeable that way. Doesn’t that break the whole idea behind it? If implementation A sets headers, and implementation B does not, we can not call `#withAddedHeader()` on the PSR-7 objects without risking getting drastically different outcomes.

This is why I initially mentioned headers specifically. Other methods will simply override whatever the factory has (or has not) set, but with headers you can run into some odd discrepancies.

**Comment by Nyholm** [comment]
Both yes and no. We want to give some freedom to the implementations at the same the we what to give the users something they can rely on. 

But I think you are correct. We should be more specific here and require more rather then less things  from the implementation.

**Comment by shadowhand** [comment]
This has been resolved in the final spec.
