### ISSUE TITLE
static factory methods for creating

### ISSUE THREAD

**Issue by S1lentium** [http-interop/http-factory#35]
Why not change all factory methods to static ones? Factories object can have a local data? Also, it was possible to implement the Factory interfaces for PSR-7 classes.

**Comment by shadowhand** [comment]
How would you activate dependency injection for static classes?

**Comment by S1lentium** [comment]
Hmm, really...  Is it really necessary to use a DI in classes that create immutable objects? If this is so necessary, the user can take care of the static field for the container, which can be initialized via the static method:
```php
public static function setContainer($container)
```

**Comment by shadowhand** [comment]
> Is it really necessary to use a DI in classes that create immutable objects?

What implementation of those immutable interfaces?

> user can take care of the static field for the container

That's not dependency injection, that is service location.
