### ISSUE TITLE
Should createResponse include a parameter for the reason phrase?

### ISSUE THREAD

**Issue by Zegnat** [http-interop/http-factory#37]
I don’t know why I didn’t run into this previously. Currently when I use `createResponse` I have to follow it up with a PSR-7 `withStatus` call to ensure a reason phrase is set:

```php
(new ResponseFactory)->createResponse(404)
    ->withStatus(404, 'Not Found');
```

This means I am double-declaring the status code, but I can’t get around that because the status code is mandatory in `withStatus`. Would it not make more sense for `createResponse` to also allow the user to set the reason phrase?

A reason phrase is not required for a minimal valid HTTP response, and I am not sure if the factory needs to be expanded just to save on a single PSR-7 method call. #9 would suggest no. I still wanted to bring up this specific case because of the weird way there PSR-7 does not allow us to add only a reason phrase and forces the redeclaration of the status code.

If it is decided that `createResponse` should **not** allow a reason phrase to be set, should the DocBlock specify what implementations need to do? Is it supposed to follow PSR-7 where “implementations MAY use the defaults as suggested in the HTTP specification”, or should the reason phrase be left empty?

**Comment by tuupola** [comment]
Looking at the interface it seems you can leave the status code out from the createResponse() call. One could avoid double-declaring the status code with something like.

```php
(new ResponseFactory)->createResponse()
    ->withStatus(404, 'Not Found');
```

**Comment by Zegnat** [comment]
> Looking at the interface it seems you can leave the status code out from the createResponse() call.

I am not sure why my brain did not register that yesterday. I blame the new year.

**Comment by mindplay-dk** [comment]
I'd say this is probably fine as-is, given that:

1. the reason phrase is optional
2. the status and reason phrase (per PSR-7) should never be set independently
3. most implementations will internally establish a meaningful default for the reason phrase

OTOH, it is perhaps more convenient, and consistent with `withStatus()`, so I wouldn't be against adding a second, optional reason phrase argument to `createResponse()`.

**Comment by oscarotero** [comment]
I'm agree with @mindplay-dk, `createResponse` should be consistent with `withStatus()`

**Comment by Zegnat** [comment]
Closing this as `createResponse` now accepts a reason phrase after #39.
